print('WITAJ W KONWENTERZE JEDNOSTEK')
print('Spis zbiorow jednostek:')
print('Spis numerow bryl: ')
print('0 - zamkniecie programu')
print('1 - tempereatura')
print('2 - powierzchnia')
print('3 - dlugosc')
print('4 - objetosc')
print('5 - masa')
print('6 - czas')
print('7 - szbkosc')

wybor = int(input('Wpisz numer twojego wyboru: '))

if wybor == 1:
    print('Spis numerow zamian:')
    print('Spis numerow bryl: ')
    print('0 - zamkniecie programu')
    print('1 - tempereatura')
    print('2 - powierzchnia')
    print('3 - dlugosc')
    print('4 - objetosc')
    print('5 - masa')
    print('6 - czas')
    print('7 - szbkosc')
